### ISSUE TITLE
У вас очень скучные обои!)

### ISSUE THREAD

**Issue by Bayselonarrend** [ahyahy/OneScriptDeclarativeForms#1]
Здравствуйте. Проект очень интересный и перспективный, но он очень слабо оформлен: Readme скучный и документация выглядит крайне устаревшей. Это, на самом деле очень важно, потому что даже самые удачные проекты часто не получают отклика и поддержки из-за таких проблем. Я бы хотел этим заняться (в рамках PR)

Если интересно, можете посмотреть оформление какого-нибудь моего репо, например [Openintegrations](https://github.com/Bayselonarrend/OpenIntegrations) и [его доки](https://openintegrations.dev/)

Я могу сделать нечто подобное, если вы согласитесь. Единственное, что я бы порекомендовал еще - поменять название проекта. Пока проект еще не в релизе, это можно сделать, а текущее название очень длинное и не персонализированное, из-за чего плохо запоминается и сложно для использования

Я бы как-нибудь поигрался со словами "OS" и "Form". Может быть около слова Фосфор, например. Там есть и OS и For) Также может подойти и просто аббревиатура OSDF

**Comment by ahyahy** [comment]
Re: [ahyahy/OneScriptDeclarativeForms] У вас очень скучные обои!) (Issue #1)


Здравствуйте, Anton.

Да, оформление не ахти какое. Это из за того, что у меня отсутствует художественный не даже талант, а хотя бы умение что то оформлять.
Такой вариант выбран оформления вообще то выбран не случайно. 
1. Гитхаб дает возможность публиковать сайт бесплатно. Денег на доменное имя нет, я на пенсии.
2. Я использую шаблоны для написания справки. Поэтому статические страницы с минимумом наглядности.
Шаблонизация дает мне скорость написания. Я создаю класс, свойство, событие для справки за минуту, две, просто заполнив поля в моей форме, всё делает дальше скрипт. И вот готово несколько html страниц.
3. Файлы cs для visual studio генерируются на основе справки. Классов много, свойства и конструкторы более менее однотипны. и скрип os читая справку генерит решение. Остается подправить ошибки. Опять же это сильно ускоряет разработку и позволяет избежать множества ошибок.
Я сильно привязан к существующим html страницам. Мне эту шаблонизацию никак нельзя менять. Время.

Не смотря на всё вышеперечисленное хочется конечно сайт для популяризации форм и сервера и может других моих разработок.
Поддерживаю Иванченко в том что односкрипту нужно придать внешний вид и писать на нём не только обслуживающие скрипты, но и программы и для других направлений. Те же игры к примеру. Осень может дать веб интерфейс, декларформы - оконную программу с функциональностью браузера... Простые мои формы - обычное оконное приложение.
Надо будет глянуть нынешние цены на доменное имя и ежегодную оплату. Может и потяну.

Имена проектам даю по традиции указывая впереди односкрипт, а затем что то отражающее суть проекта. Фантазии на большее не хватает.
Если хотите помочь, я только рад буду. Подключайтесь.
Ваши проекты я видел конечно. Мне до них далеко.

Сейчас я время от времени в деклар формах нахожу лучшие решения и кое что переписываю, оптимизирую, поэтому меняю и справку и в Readme что то. Версии 1.0 ещё нет  и как сейчас оформлять не имея полной картины хотя бы первого варианта не знаю. Вот понял сегодня что неправильно описал работу программы с main.js
Переделаю в ближайшее время. main.js и все другие файлы будут статичны. Программисту к ним нужно будет  только добавить стартовый сценарий и может другие сценарии в каталог Классы.


-- 
С уважением,
 Алёшечкин                         ***@***.***

**Comment by Bayselonarrend** [comment]
> Гитхаб дает возможность публиковать сайт бесплатно. Денег на доменное имя нет, я на пенсии

Я использую [neocities](https://neocities.org/). Он также бесплатный, но там сайты можно разделять. Для публикации также можно использовать Github Actions. В целом, эту часть я могу взять на себя, нет никаких проблем, сделать это в данный момент как вторую справку

> Я использую шаблоны для написания справки. Поэтому статические страницы с минимумом наглядности.
Шаблонизация дает мне скорость написания

А какой формат шаблона? Понятно, что писать каждую страницу руками - это не вариант, но возможно я смогу распарсить ваш существующий формат и запихнуть его в более современный генератор документов

>Я сильно привязан к существующим html страницам. Мне эту шаблонизацию никак нельзя менять

В целом, я думаю, все может получиться, если завязаться на существующий формат шаблона и генерировать от этих страниц уже новую документацию, которая не будет затрагивать html файлы

>Имена проектам даю по традиции указывая впереди односкрипт, а затем что то отражающее суть проекта. Фантазии на большее не хватает.

Я бы сократил хотя бы до OSDF, если честно

>Версии 1.0 ещё нет  и как сейчас оформлять не имея полной картины хотя бы первого варианта не знаю. Вот понял сегодня что неправильно описал работу программы с main.js

Не думаю, что внутренняя кухня - это вообще предмет для документации. В первую очередь нужно описание методов использования, т.к. если в большое количество новой информации, которая пользователю нужна для работы, еще добавить информации о том, как это все происходит, то он может запутаться. Это выглядит интересно как факультативная информация на отдельной странице, но не как что-то, с чего все должно начинаться

**Comment by ahyahy** [comment]
Re: [ahyahy/OneScriptDeclarativeForms] У вас очень скучные обои!) (Issue #1)

Здравствуйте, Anton.

Вы писали 11 сентября 2024 г., 18:29:09:

Я использую neocities. Он также бесплатный, но там сайты можно разделять. 

Вроде годится. Почитаю повнимательнее. А вариант оставления на гитхаб со статичными html рассматривается? Или всё таки для охвата большей аудитории лучше сменить? А что значит сайты можно разделять?

сделать это в данный момент как вторую справку

Хороший вариант.

А какой формат шаблона? 

Да у меня там всё индивидуально, всё под меня сделано. Вот закачал на гитхаб
https://github.com/ahyahy/OneScriptDeclarativeForms/tree/main/tests 
Это то, что я запускаю чтобы создать html классов, свойств, событий ...
После этого полученные html редактирую одновременно проверяя правильность работы библиотеки.
Редактирование заключается в написании примера для демонстрации синтаксиса. Разделы Пример и Полный пример кода. 

Я бы сократил хотя бы до OSDF, если честно

OSDF аббревиатура. Аббревиатура воспринимается хорошо, когда она всем известна. Из OneScriptDeclarativeForms уже можно какую то инфолрмацию получить, хоть и длинно. Можно OSDeclarativeForms. Или OSDForms.

Не думаю, что внутренняя кухня - это вообще предмет для документации. В первую очередь нужно описание методов использования, т.к. если в большое количество новой информации, которая пользователю нужна для работы, еще добавить информации о том, как это все происходит, то он может запутаться. Это выглядит интересно как факультативная информация на отдельной странице, но не как что-то, с чего все должно начинаться

Да, надо кухню отдельно вынести.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>
-- 
С уважением,
 Алёшечкин                         ***@***.***

**Comment by Bayselonarrend** [comment]
С Readme пока как-то вот так получилось

https://github.com/Bayselonarrend/OneScriptDeclarativeForms

**Comment by ahyahy** [comment]
Отлично получилось.
Нужно подправить вот это:
................................
Она обеспечивает фоновое выполнение обработчиков и связь OS-сценария с окном программы на основе библиотеки OneScriptClientServer

Она обеспечивает выполнение обработчиков событий и связь OS-сценария с окном программы на основе библиотеки OneScriptClientServer
................................
Благодаря нему

Благодаря ему
................................
Логика приложения описывается на язык 1С при помощий

Логика приложения описывается на языкe 1С при помощи
................................
TODO: Дописать дальнейшие шаги

Прочитать указанный ниже раздел документации и согласно этой информации организовать каталог будущей программы.
................................
Спасибо, жду PR.

**Comment by Bayselonarrend** [comment]
Сделал PR на Readme. Пока честно говоря не придумал, что делать с доками (не особо владею C# к тому же), посмотрим ближе к релизу. Хочу сейчас сам еще поэкспериментировать с nw.js, может узнаю больше - будет понятнее

Спасибо
